// Config catalogue: one entry per config file. Text of each file is injected at build time as FILES[file].
const CONFIGS = [
  { id:'flins_lc', file:'flins_lunarcharged.json', char:'Flins', reaction:'Лунный заряд', tag:'lunarcharged',
    cons:6, weapon:null, role:'Главный на лунном заряде, доля реакции 0.6',
    team:[['Columbina',6],['Ineffa',1],['Nicole',2]],
    rotation:'E N2 E sQ N4D N3 E sQ N4D N2 E sQ N4',
    source:'KQM',
    warnings:['Николь ульт не жмёт: её переключатель Q не включай. C1 Unity работает без Q.'],
    estimates:[] },
  { id:'ineffa_lc', file:'ineffa_lunarcharged.json', char:'Ineffa', reaction:'Лунный заряд', tag:'lunarcharged',
    cons:1, weapon:'Сигна', role:'Второй на лунном заряде, доля 0.3',
    team:[['Flins',6],['Columbina',6],['Nicole',2]],
    rotation:'E Q / E (Q через ротацию)', source:'KQM',
    warnings:[], estimates:[] },
  { id:'columbina_lc', file:'columbina_lunarcharged.json', char:'Columbina', reaction:'Лунный заряд', tag:'lunarcharged',
    cons:6, weapon:'Сигна R1', role:'Саппорт, Q каждую ротацию',
    team:[['Flins',6],['Ineffa',1],['Nicole',2]],
    rotation:'Q, E, 9 тиков Gravity Ripple, 3 Interference', source:'KQM',
    warnings:['C4 Коломбины GO считает не так, как игра: сверься с тредом «Коломбина Lunar-Charged».'],
    estimates:[] },
  { id:'columbina_lcr', file:'columbina_lunarcrystallize.json', char:'Columbina', reaction:'Лунная кристаллизация', tag:'lunarcrystallize',
    cons:6, weapon:'Сигна R1', role:'Второй на кристаллизации, доля 0.3',
    team:[['Zibai',1],['Linnea',2],['Xilonen',2]],
    rotation:'18 с: Q, E, 9 тиков, 5 Interference', source:'KQM + код gcsim',
    warnings:['C4 Коломбины для этого конфига в GO выключи.'],
    estimates:['Около 28 ударов Moondrift за ротацию, оценка.'] },
  { id:'zibai_lcr', file:'zibai_lunarcrystallize.json', char:'Zibai', reaction:'Лунная кристаллизация', tag:'lunarcrystallize',
    cons:1, weapon:'Сигна R1', role:'Главный на кристаллизации, доля 0.6',
    team:[['Columbina',6],['Linnea',2],['Xilonen',2]],
    rotation:'Q, 5 Stride, 3 × N4', source:'KQM',
    warnings:['Переключатель C1 держи выключенным: +220% уже стоит в bonusStats первой строки.'],
    estimates:['Около 28 ударов реакции за ротацию, оценка.'] },
  { id:'linnea_lcr', file:'linnea_lunarcrystallize.json', char:'Linnea', reaction:'Лунная кристаллизация', tag:'lunarcrystallize',
    cons:2, weapon:'Сигна R1', role:'Вне поля, одиночный E без Q',
    team:[['Zibai',1],['Columbina',6],['Xilonen',2]],
    rotation:'1 E, 3.5 Hammer, 12 Pummeler', source:'KQM (Super-режим)',
    warnings:['C1 в GO (+75% защиты) действует на все удары кристаллизации, в игре только на 6 за 10 с.'],
    estimates:['Число Hammer и Pummeler и доля в Harmony оценены: в TCL пусто, в gcsim Линнеи нет.'] },
  { id:'sandrone_sc', file:'sandrone_stellarconduct.json', char:'Sandrone', reaction:'Звёздный проводник', tag:'stellarconduct',
    cons:0, weapon:'Сигна Мавуики', role:'Главный ДД',
    team:[['YaeMiko',1],['Odette',2],['Nicole',2]],
    rotation:'Q, 3 E, 3 CA', source:'KQM',
    warnings:['В GO нет строки реакции stellarconduct, урон считается через таланты.'],
    estimates:['Число лучей и взмахов в CA оценено.'] },
  { id:'yae_sc', file:'yae_stellarconduct.json', char:'YaeMiko', reaction:'Звёздный проводник', tag:'stellarconduct',
    cons:1, weapon:'Сигна Нефер', role:'Саппорт-ДД вне поля',
    team:[['Sandrone',0],['Odette',2],['Nicole',2]],
    rotation:'3 E, 18 ударов Sakura, 9 SC', source:'KQM',
    warnings:['Moon of Truth у сигны Нефер вне Lunar-Bloom в GO лучше не включать: в игре он не работает.'],
    estimates:[] },
  { id:'odette_sc', file:'odette_stellarconduct.json', char:'Odette', reaction:'Звёздный проводник', tag:'stellarconduct',
    cons:2, weapon:'Сигна Кадзухи', role:'Саппорт, Q не жмёт',
    team:[['Sandrone',0],['YaeMiko',1],['Nicole',2]],
    rotation:'E + Coda, 10 двойных ударов', source:'KQM',
    warnings:[], estimates:['Тики Coda и число Double Plume/Wing оценены.'] },
  { id:'varka_swirl', file:'varka_anemopyro.json', char:'Varka', reaction:'Пиро рассеивание', tag:'swirl',
    cons:6, weapon:'Сигна R1', role:'Главный ДД, без Q',
    team:[['Durin',2],['Nicole',2],['Prune',6]],
    rotation:'E, 3 sE, 3 sC, 9 N', source:'KQM',
    warnings:['Николь ульт не жмёт: её переключатель Q не включай.'], estimates:[] },
  { id:'durin_swirl', file:'durin_pyroswirl.json', char:'Durin', reaction:'Пиро рассеивание', tag:'swirl',
    cons:2, weapon:'Сигна R1', role:'Вне поля, Белое пламя',
    team:[['Varka',6],['Nicole',2],['Prune',6]],
    rotation:'2 E, 1 Q, 20 ударов дракона', source:'KQM',
    warnings:['Форму Q в GO ставь White.'], estimates:[] },
  { id:'skirk_freeze', file:'skirk_freeze.json', char:'Skirk', reaction:'Заморозка', tag:'freeze',
    cons:2, weapon:'Сигна R1', role:'Главный ДД, ротация «до C6»',
    team:[['Escoffier',1],['Furina',6],['Mona',1]],
    rotation:'E, N2D, N2D, N2Q, N2D, N2D, N3W, N2D, N2D, N3W, N2CA D, N5W', source:'Vortex Gaming',
    warnings:['Void Rift = 0, Death’s Crossing = 3.'],
    estimates:['Число клинков C1 оценено.'] },
  { id:'furina_skirk', file:'furina_skirkteam.json', char:'Furina', reaction:'Заморозка (саппорт)', tag:'freeze',
    cons:6, weapon:'Фавоний', role:'Саппорт вне поля',
    team:[['Skirk',2],['Escoffier',1],['Mona',1]],
    rotation:'E D N2 Q, ротация 21 с', source:'KQM',
    warnings:['C6 включи, Pneuma выключи, Salon Members = 4.'], estimates:[] },
  { id:'escoffier_skirk', file:'escoffier_skirkteam.json', char:'Escoffier', reaction:'Заморозка (саппорт)', tag:'freeze',
    cons:1, weapon:'Сигна R1', role:'Саппорт вне поля',
    team:[['Skirk',2],['Furina',6],['Mona',1]],
    rotation:'E Q, 19 Parfait за 21 с', source:'KQM',
    warnings:['Пассивка требует 4 гидро/крио в отряде GO, собери отряд там же.'],
    estimates:['Parfait 18–20 за ротацию, взято 19.'] },
];
