// Config catalogue: one entry per config file. Text of each file is injected at build time as FILES[file].
const CONFIGS = [
  { id:'flins_lc', file:'flins_lunarcharged.json', char:'Flins', reaction:'Лунный заряд', tag:'lunarcharged',
    cons:6, weapon:null, role:'Главный на лунном заряде, доля реакции 0.6',
    team:[['Columbina',6],['Ineffa',1],['Nicole',2]],
    rotation:'E N2 E sQ N4D N3 E sQ N4D N2 E sQ N4',
    source:'KQM',
    warnings:['Николь ульт не жмёт: её переключатель Q не включай. C1 Unity работает без Q.'],
    estimates:[] },
  { id:'ineffa_lc', file:'ineffa_lunarcharged.json', char:'Ineffa', reaction:'Лунный заряд', tag:'lunarcharged',
    cons:1, weapon:'Сигна', role:'Второй на лунном заряде, доля 0.3',
    team:[['Flins',6],['Columbina',6],['Nicole',2]],
    rotation:'E Q / E (Q через ротацию)', source:'KQM',
    warnings:[], estimates:[] },
  { id:'columbina_lc', file:'columbina_lunarcharged.json', char:'Columbina', reaction:'Лунный заряд', tag:'lunarcharged',
    cons:6, weapon:'Сигна R1', role:'Саппорт, Q каждую ротацию',
    team:[['Flins',6],['Ineffa',1],['Nicole',2]],
    rotation:'Q, E, 9 тиков Gravity Ripple, 3 Interference', source:'KQM',
    warnings:['C4 Коломбины GO считает не так, как игра: сверься с тредом «Коломбина Lunar-Charged».'],
    estimates:[] },
  { id:'columbina_lcr', file:'columbina_lunarcrystallize.json', char:'Columbina', reaction:'Лунная кристаллизация', tag:'lunarcrystallize',
    cons:6, weapon:'Сигна R1', role:'Второй на кристаллизации, доля 0.3',
    team:[['Zibai',1],['Linnea',2],['Xilonen',2]],
    rotation:'18 с: Q, E, 9 тиков, 5 Interference', source:'KQM + код gcsim',
    warnings:['C4 Коломбины для этого конфига в GO выключи.'],
    estimates:['Около 28 ударов Moondrift за ротацию, оценка.'] },
  { id:'zibai_lcr', file:'zibai_lunarcrystallize.json', char:'Zibai', reaction:'Лунная кристаллизация', tag:'lunarcrystallize',
    cons:1, weapon:'Сигна R1', role:'Главный на кристаллизации, доля 0.6',
    team:[['Columbina',6],['Linnea',2],['Xilonen',2]],
    rotation:'Q, 5 Stride, 3 × N4', source:'KQM',
    warnings:['Переключатель C1 держи выключенным: +220% уже стоит в bonusStats первой строки.'],
    estimates:['Около 28 ударов реакции за ротацию, оценка.'] },
  { id:'linnea_lcr', file:'linnea_lunarcrystallize.json', char:'Linnea', reaction:'Лунная кристаллизация', tag:'lunarcrystallize',
    cons:2, weapon:'Сигна R1', role:'Вне поля, одиночный E без Q',
    team:[['Zibai',1],['Columbina',6],['Xilonen',2]],
    rotation:'1 E, 3.5 Hammer, 12 Pummeler', source:'KQM (Super-режим)',
    warnings:['C1 в GO (+75% защиты) действует на все удары кристаллизации, в игре только на 6 за 10 с.'],
    estimates:['Число Hammer и Pummeler и доля в Harmony оценены: в TCL пусто, в gcsim Линнеи нет.'] },
  { id:'sandrone_sc', file:'sandrone_stellarconduct.json', char:'Sandrone', reaction:'Звёздный проводник', tag:'stellarconduct',
    cons:0, weapon:'Сигна Мавуики', role:'Главный ДД',
    team:[['YaeMiko',1],['Odette',2],['Nicole',2]],
    rotation:'Q, 3 E, 3 CA', source:'KQM',
    warnings:['В GO нет строки реакции stellarconduct, урон считается через таланты.'],
    estimates:['Число лучей и взмахов в CA оценено.'] },
  { id:'yae_sc', file:'yae_stellarconduct.json', char:'YaeMiko', reaction:'Звёздный проводник', tag:'stellarconduct',
    cons:1, weapon:'Сигна Нефер', role:'Саппорт-ДД вне поля',
    team:[['Sandrone',0],['Odette',2],['Nicole',2]],
    rotation:'3 E, 18 ударов Sakura, 9 SC', source:'KQM',
    warnings:['Moon of Truth у сигны Нефер вне Lunar-Bloom в GO лучше не включать: в игре он не работает.'],
    estimates:[] },
  { id:'odette_sc', file:'odette_stellarconduct.json', char:'Odette', reaction:'Звёздный проводник', tag:'stellarconduct',
    cons:2, weapon:'Сигна Кадзухи', role:'Саппорт, Q не жмёт',
    team:[['Sandrone',0],['YaeMiko',1],['Nicole',2]],
    rotation:'E + Coda, 10 двойных ударов', source:'KQM',
    warnings:[], estimates:['Тики Coda и число Double Plume/Wing оценены.'] },
  { id:'varka_swirl', file:'varka_anemopyro.json', char:'Varka', reaction:'Пиро рассеивание', tag:'swirl',
    cons:6, weapon:'Сигна R1', role:'Главный ДД, без Q',
    team:[['Durin',2],['Nicole',2],['Prune',6]],
    rotation:'E, 3 sE, 3 sC, 9 N', source:'KQM',
    warnings:['Николь ульт не жмёт: её переключатель Q не включай.'], estimates:[] },
  { id:'durin_swirl', file:'durin_pyroswirl.json', char:'Durin', reaction:'Пиро рассеивание', tag:'swirl',
    cons:2, weapon:'Сигна R1', role:'Вне поля, Белое пламя',
    team:[['Varka',6],['Nicole',2],['Prune',6]],
    rotation:'2 E, 1 Q, 20 ударов дракона', source:'KQM',
    warnings:['Форму Q в GO ставь White.'], estimates:[] },
  { id:'skirk_freeze', file:'skirk_freeze.json', char:'Skirk', reaction:'Заморозка', tag:'freeze',
    cons:2, weapon:'Сигна R1', role:'Главный ДД, ротация «до C6»',
    team:[['Escoffier',1],['Furina',6],['Mona',1]],
    rotation:'E, N2D, N2D, N2Q, N2D, N2D, N3W, N2D, N2D, N3W, N2CA D, N5W', source:'Vortex Gaming',
    warnings:['Void Rift = 0, Death’s Crossing = 3.'],
    estimates:['Число клинков C1 оценено.'] },
  { id:'furina_skirk', file:'furina_skirkteam.json', char:'Furina', reaction:'Заморозка (саппорт)', tag:'freeze',
    cons:6, weapon:'Фавоний', role:'Саппорт вне поля',
    team:[['Skirk',2],['Escoffier',1],['Mona',1]],
    rotation:'E D N2 Q, ротация 21 с', source:'KQM',
    warnings:['C6 включи, Pneuma выключи, Salon Members = 4.'], estimates:[] },
  { id:'escoffier_skirk', file:'escoffier_skirkteam.json', char:'Escoffier', reaction:'Заморозка (саппорт)', tag:'freeze',
    cons:1, weapon:'Сигна R1', role:'Саппорт вне поля',
    team:[['Skirk',2],['Furina',6],['Mona',1]],
    rotation:'E Q, 19 Parfait за 21 с', source:'KQM',
    warnings:['Пассивка требует 4 гидро/крио в отряде GO, собери отряд там же.'],
    estimates:['Parfait 18–20 за ротацию, взято 19.'] },
];

// Plain Russian names for every line of every config, in file order (what the line counts, for a player).
const CFG_RU = {
  columbina_lc: ['Q: урон взрыва', 'E: урон при касте', 'E: тики Gravity Ripple', 'E: Gravity Interference (лунный заряд), вместе с C1', 'Реакция лунный заряд: 6 срабатываний с долей 0.3 и 4 с долей 0.05'],
  columbina_lcr: ['Q: урон взрыва', 'E: урон при касте', 'E: тики Gravity Ripple, раз в 1,95 с за ротацию 18 с', 'E: Gravity Interference (C1 при E и около 4 от C2)', 'Реакция лунная кристаллизация: около 28 ударов Moondrift × доля 0.3'],
  zibai_lcr: ['Stride: 2-й удар первого Stride (C1 +220%, переключатель C1 держи выключенным)', 'Stride: 2-й удар остальных четырёх', 'Stride: 1-й удар, 5 за режим (C1)', 'Обычная атака 4: доп. удар (Ascendant Gleam)', 'Обычная атака 1 (3 перед N4 и 1 перед Q)', 'Обычная атака 2', 'Обычная атака 3, 2 удара × 3', 'Обычная атака 4', 'Q: первый удар', 'Q: второй удар (лунная кристаллизация)', 'Реакция лунная кристаллизация: около 28 ударов (8 Harmony × 3 и A4 Коломбины) × доля 0.6'],
  linnea_lcr: ['E: Heavy Overdrive Hammer, примерно раз в 5 с (оценка)', 'E: Pummeler, около 6 атак × 2', 'Реакция лунная кристаллизация от C2: 3,5 × доля 0.05'],
  flins_lc: ['Q: урон грома', 'Q: дополнительный гром (Ascendant Gleam)', 'E: Spearstorm', 'C2: первая обычная атака после Spearstorm', 'Реакция лунный заряд: 7 срабатываний × доля 0.6', 'Николь C1 Unity: раз в 6 с, её Q не нужен', 'Обычная атака 1', 'Обычная атака 2', 'Обычная атака 3', 'Обычная атака 4, 2 удара × 3'],
  ineffa_lc: ['Q: урон взрыва (жмётся через ротацию)', 'E: урон при касте', 'E: Биргитта, раз в 2 с (2 × 20 с)', 'Пассивка A1: раз в 3,5 с', 'Реакция лунный заряд: 14 срабатываний × доля 0.3'],
  sandrone_sc: ['Заряженная атака: лучи, около 3 за атаку × 3', 'Заряженная атака: взмах огнём, около 1 за атаку', 'E: первый Prism Shot', 'E: второй Prism Shot (A1 × 4)', 'Q: бомбардировка × 3', 'Q: луч (A1 Refined Tactics)', 'Николь C1 Unity: откат 6 с, поле около 12 с'],
  yae_sc: ['E: удары Сакуры ур. 3 (3 тотема × 6, без усиленных)', 'Усиленные удары Сакуры ур. 3, каждый третий', 'Удар звёздного проводника при усиленном ударе', 'A1: удар за каждый E с 3 тотемами'],
  odette_sc: ['E: урон при касте', 'E: тики Coda (оценка)', 'E: финальный удар Coda (звёздный проводник)', 'C1: доп. удар после Coda', 'E: Double Plume за 20 с (оценка)', 'E: Double Plume, часть звёздного проводника', 'E: Double Wing за 20 с (оценка)', 'E: Double Wing, часть звёздного проводника'],
  varka_swirl: ['E (тап): вход в Sturm und Drang', 'C1: первые Four Winds 200%, пиро часть', 'C1: первые Four Winds 200%, анемо часть', 'Four Winds × 2, пиро часть', 'Four Winds × 2, анемо часть', 'C6: Azure Devour × 3, по 2 пиро удара', 'C6: Azure Devour × 3, по 2 анемо удара', 'C2: удар после каждого sE и sC', 'Обычная атака 1, 3 серии', 'Обычная атака 2, анемо', 'Обычная атака 2, пиро', 'Обычная атака 3, анемо', 'Обычная атака 3, пиро', 'Обычная атака 4, пиро', 'Обычная атака 4, анемо', 'Николь C1 Unity: откат 6 с, поле около 12 с'],
  durin_swirl: ['Второй E: Confirmation of Purity', 'Q: удар Purity 1', 'Q: удар Purity 2', 'Q: удар Purity 3', 'Q: Белое пламя, 20 тиков (10 с бонусом A4 и 10 без, пересчитано в 15,7)'],
  skirk_freeze: ['Seven-Phase Flash: обычная атака 1, 11 цепочек', 'Seven-Phase Flash: обычная атака 2, 11 цепочек', 'Seven-Phase Flash: обычная атака 3, 2 удара × 3', 'Seven-Phase Flash: обычная атака 4, 2 удара × 1', 'Seven-Phase Flash: обычная атака 5', 'Seven-Phase Flash: заряженная атака, 3 удара', 'C1: кристальные клинки, 3 разлома после sQ и 3 после CA (оценка)'],
  furina_skirk: ['Обычная атака 1 после E (C6, Ousia)', 'Обычная атака 2 после E (C6, Ousia)', 'E: пузырь Ousia, 1 E за ротацию', 'E: Usher, примерно раз в 3,4 с', 'E: Chevalmarin, примерно раз в 1,6 с', 'E: Crabaletta, примерно раз в 5,2 с', 'Q: урон взрыва'],
  escoffier_skirk: ['E: первый удар', 'E: Surging Blade (Ousia), 1 за E', 'E: Frosty Parfait, примерно раз в 0,98 с за ротацию 21 с (оценка 18–20)', 'Q: урон взрыва'],
};
